name: Check Solution
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pytest

      - name: Download hidden tests
        env:
          TOKEN: ${{ secrets.TESTS_ACCESS_TOKEN }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "::error::PAT token is not configured!"
            exit 1
          fi
          git clone --depth 1 --filter=blob:none --sparse https://$TOKEN@github.com/${{ github.repository_owner }}/python-practice-tests.git
          cd python-practice-tests
          git sparse-checkout set tests
          cd ..
          mv python-practice-tests/tests .
          rm -rf python-practice-tests

      - name: Determine tests to run
        id: test-filter
        run: |
          TESTS_TO_RUN=()
          
          # Ищем изменения в любых подпапках src/
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == src/*/task_*/*.py ]]; then
              category=$(echo $file | cut -d'/' -f2)
              task_num=$(echo $file | grep -oP 'task_\K\d+')
              test_file="tests/${category}/test_task_${task_num}.py"
              
              if [ -f "$test_file" ]; then
                TESTS_TO_RUN+=("$test_file")
              fi
            fi
          done

          if [ ${#TESTS_TO_RUN[@]} -eq 0 ]; then
            echo "::notice::No specific tasks changed, running all tests"
            TESTS_TO_RUN=("tests/")
          fi

          echo "test_files=${TESTS_TO_RUN[*]}" >> $GITHUB_OUTPUT
          echo "Will run tests for: ${TESTS_TO_RUN[*]}"

      - name: Run tests
        run: pytest -v ${{ steps.test-filter.outputs.test_files }}

      - name: Cleanup
        run: rm -rf tests